# Generated by Django 4.0.2 on 2022-02-21 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlucoseRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose_range', models.IntegerField(verbose_name='Zakres glikozy')),
            ],
            options={
                'verbose_name': 'Zakres glukozy',
                'verbose_name_plural': 'Zakresy glukozy',
            },
        ),
        migrations.CreateModel(
            name='TimeOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(max_length=50, verbose_name='Posiłek')),
            ],
            options={
                'verbose_name': 'Posiłek',
                'verbose_name_plural': 'Posiłki',
            },
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Data pomiaru')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Czas pomiaru')),
                ('measurement', models.IntegerField(verbose_name='Pomiar glukozy')),
                ('information', models.TextField(blank=True, null=True, verbose_name='Informacje')),
                ('time_of_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diary', to='diary.timeofday', verbose_name='Rodzaj posiłku')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diary', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Dziennik',
                'verbose_name_plural': 'Dziennik',
            },
        ),
    ]
